yarnPath: .yarn/releases/yarn-3.0.2.cjs

packageExtensions:
  'http-proxy-middleware@^2.0.0':
    dependencies:
      '@types/express': '^4.17.13'
  '@storybook/addons@^6.3.8':
    dependencies:
      '@types/webpack-env': '^1.16.0'
  '@storybook/react@^6.3.8':
    dependencies:
      '@storybook/client-api': '^6.3.8'
      '@types/node': '^14.17.15'
  '@storybook/theming@^6.3.8':
    dependencies:
      '@emotion/serialize': '^0.11.16'
      '@emotion/utils': '^0.11.3'
  'redux-persist@^6.0.0':
    dependencies:
      '@types/react': '^16.14.15'
      'react': '^16.14.0'
  'apollo-server-core@^2.25.2':
    dependencies:
      '@types/node': '^14.17.15'
  'apollo-server@^2.25.2':
    dependencies:
      '@types/express': '^4.17.13'
      '@types/node': '^14.17.15'
  'graphql-subscriptions@^1.0.0':
    dependencies:
      '@types/node': '^14.17.15'
  'subscriptions-transport-ws@^0.9.19':
    dependencies:
      '@types/node': '^14.17.15'
      '@types/ws': '^7.4.7'
  'knex@^0.19.5':
    dependencies:
      '@types/node': '^14.17.15'
      'sqlite3': '^5.0.2'
  'react-select@^5.0.0':
    dependencies:
      '@emotion/serialize': '^1.0.2'
  '@chakra-ui/button@^1.4.3':
    dependencies:
      '@chakra-ui/react-utils': '^1.1.2'
  '@chakra-ui/switch@^1.2.10':
    peerDependencies:
      'framer-motion': '3.x || 4.x'
  '@chakra-ui/media-query@^1.1.2':
    peerDependencies:
      '@emotion/react': '^11.0.0'
      '@emotion/styled': '^11.0.0'
  '@chakra-ui/skeleton@^1.1.18':
    peerDependencies:
      '@emotion/react': '^11.0.0'
      '@emotion/styled': '^11.0.0'
  '@chakra-ui/accordion@^1.3.6':
    peerDependencies:
      'framer-motion': '3.x || 4.x'
  '@mswjs/data@^0.5.1':
    dependencies:
      'debug': '^4.3.2'
  'msw@^0.35.0':
    dependencies:
      'debug': '^4.3.2'
