yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  'http-proxy-middleware@^2.0.0':
    dependencies:
      '@types/express': '^4.17.13'
  '@storybook/addons@^6.3.8':
    dependencies:
      '@types/webpack-env': '^1.16.0'
  '@storybook/react@^6.3.8':
    dependencies:
      '@storybook/client-api': '^6.3.8'
      '@types/node': '*'
  '@storybook/theming@^6.3.8':
    dependencies:
      '@emotion/serialize': '^0.11.16'
      '@emotion/utils': '^0.11.3'
  'redux-persist@^6.0.0':
    dependencies:
      '@types/react': '*'
      'react': '*'
  'apollo-server-core@^3.4.0':
    dependencies:
      '@types/node': '*'
  'tarn@^3.0.1':
    dependencies:
      '@types/node': '*'
  '@chakra-ui/switch@^1.2.10':
    peerDependencies:
      'framer-motion': '3.x || 4.x || 5.x'
  '@chakra-ui/media-query@^1.1.2':
    peerDependencies:
      '@emotion/react': '^11.0.0'
      '@emotion/styled': '^11.0.0'
  '@chakra-ui/skeleton@^1.1.18':
    peerDependencies:
      '@emotion/react': '^11.0.0'
      '@emotion/styled': '^11.0.0'
  '@chakra-ui/accordion@^1.3.6':
    peerDependencies:
      'framer-motion': '3.x || 4.x || 5.x'
  '@mswjs/data@*':
    dependencies:
      'debug': '^4.3.2'
  'msw@*':
    dependencies:
      'debug': '^4.3.2'
