yarnPath: .yarn/releases/yarn-3.0.2.cjs

packageExtensions:
  'http-proxy-middleware@^2.0.0':
    dependencies:
      '@types/express': '^4.17.13'
  '@storybook/addons@^6.3.8':
    dependencies:
      '@types/webpack-env': '^1.16.0'
  '@storybook/react@^6.3.8':
    dependencies:
      '@storybook/client-api': '^6.3.8'
      '@types/node': '^14.17.15'
  '@storybook/theming@^6.3.8':
    dependencies:
      '@emotion/serialize': '^0.11.16'
      '@emotion/utils': '^0.11.3'
  'redux-persist@^6.0.0':
    dependencies:
      '@types/react': '^16.14.15'
      'react': '^16.14.0'
  'apollo-server-core@^2.25.2':
    dependencies:
      '@types/node': '^14.17.15'
  'apollo-server@^2.25.2':
    dependencies:
      '@types/express': '^4.17.13'
      '@types/node': '^14.17.15'
  'graphql-subscriptions@^1.0.0':
    dependencies:
      '@types/node': '^14.17.15'
  'subscriptions-transport-ws@^0.9.19':
    dependencies:
      '@types/node': '^14.17.15'
      '@types/ws': '^7.4.7'
  'knex@^0.19.5':
    dependencies:
      '@types/node': '^14.17.15'
      'sqlite3': '^5.0.2'
