yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  '@storybook/react@*':
    dependencies:
      '@types/node': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/serialize': '^0.11.16'
      '@emotion/utils': '^0.11.3'
  'apollo-server-core@^3.4.0':
    dependencies:
      '@types/node': '*'
  'tarn@^3.0.1':
    dependencies:
      '@types/node': '*'
