packages:
  - extension
  - packages/*
  - packages/d3-state-visualizer/examples/tree
  - packages/react-dock/demo
  - packages/react-json-tree/examples
  - packages/redux-devtools/examples/counter
  - packages/redux-devtools/examples/todomvc
  - packages/redux-devtools-inspector-monitor/demo
  - packages/redux-devtools-inspector-monitor-test-tab/demo
  - packages/redux-devtools-rtk-query-monitor/demo
  - packages/redux-devtools-slider-monitor/examples/todomvc
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@swc/core'
  - chromedriver
  - electron
  - esbuild
  - msw
  - sqlite3
patchedDependencies:
  '@dnd-kit/core': patches/@dnd-kit__core.patch
  '@dnd-kit/sortable': patches/@dnd-kit__sortable.patch
  react-icons: patches/react-icons.patch
